<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>perimeter_miner</name>
  <version>1.0.0</version>
  <description>Perimeter-patrolling unmanned robotic complex for mine clearance operations</description>
  
  <maintainer email="student@university.edu">student</maintainer>
  <license>MIT</license>
  
  <buildtool_depend>ament_cmake</buildtool_depend>
  
  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>std_msgs</depend>
  <depend>builtin_interfaces</depend>
  <depend>rosidl_default_generators</depend>
  <depend>yaml_cpp_vendor</depend>
  <depend>perimeter_msgs</depend>
  
  <exec_depend>ros2launch</exec_depend>
  
  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  
  <member_of_group>ros2_control_plugin</member_of_group>
  
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
